name: restaurante_escola_app
description: Restaurante Escola - Guilherme Rabelo
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_launcher_icons: ^0.9.1
  fluttertoast: ^8.0.8
  smart_page_navigation: ^1.1.2
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  provider: ^6.0.1
  flutter_secure_storage: ^4.2.1
  dio: ^4.0.1
  json_annotation: ^4.3.0

flutter_icons:
  image_path: "assets/images/restaurant-school-icon.png"
  android: true

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^6.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2


flutter:
  assets:
    - assets/images/

  uses-material-design: true
